export const GET_POSTS = 'GET_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const SHOW_POST_MODAL = 'SHOW_POST_MODAL';
export const SUBMIT_POST = 'SUBMIT_POST';
export const POST_SUBMITTED = 'POST_SUBMITTED';
export const POST_FETCH_FAILED = 'POST_FETCH_FAILED';

export const SET_USER = 'SET_USER';
export const LOGGED_IN = 'LOGGED_IN';
export const SET_AUTH_RELOAD = 'SET_AUTH_RELOAD';
export const LOG_OUT_USER = 'LOG_OUT_USER';

export const POST_USER_COMMENTS = 'POST_USER_COMMENTS';
export const POST_COMMENTS = 'POST_COMMENTS';
export const GET_USER_ID = 'GET_USER_ID';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_COMMENT_FETCH_FAILED = 'GET_COMMENT_FETCH_FAILED';
export const POST_USER_ID = 'POST_USER_ID';

export const POST_TASK_LIST = 'POST_TASK_LIST'
